# EDA

In [1]:
import pandas as pd
import os

path = "../data/raw" 
products_df = pd.read_csv(f"{path}/product_info.csv")
products_df.columns

Index(['product_id', 'product_name', 'brand_id', 'brand_name', 'loves_count',
       'rating', 'reviews', 'size', 'variation_type', 'variation_value',
       'variation_desc', 'ingredients', 'price_usd', 'value_price_usd',
       'sale_price_usd', 'limited_edition', 'new', 'online_only',
       'out_of_stock', 'sephora_exclusive', 'highlights', 'primary_category',
       'secondary_category', 'tertiary_category', 'child_count',
       'child_max_price', 'child_min_price'],
      dtype='object')

In [2]:
use_cols = ["product_id","product_name", "brand_name", "loves_count", "rating", "reviews", "ingredients", "price_usd", "primary_category"]
products_df = products_df[use_cols]
products_df.sample(5)

,product_id,product_name,brand_name,loves_count,rating,reviews,ingredients,price_usd,primary_category
4437,P482693,Water Bank Blue Hyaluronic Cream Moisturizer,LANEIGE,48729,3.9928,699.0,"['Water / Aqua / Eau, Butylene Glycol, Glyceri...",40.0,Skincare
6637,P439672,Rose Quartz Facial Roller,SEPHORA COLLECTION,29366,3.7111,135.0,NaN,22.0,Skincare
4344,P428639,Mini The Renewal Oil,La Mer,6304,4.3077,13.0,"['Limnanthes Alba (Meadowfoam) Seed Oil, Dimet...",145.0,Skincare
5163,P9864,Angel Eau de Parfum,Mugler,32020,4.0626,1231.0,"['Alcohol, Fragrance, Water, Butylphenyl Methy...",95.0,Fragrance
7996,P468712,Naked Wild West Eyeshadow Palette,Urban Decay,49653,4.4483,890.0,"['Spur:', 'Mica, Talc, Ci 77891 / Titanium Dio...",49.0,Makeup

In [3]:
print(len(products_df))
print(products_df["product_id"].nunique()) # checking for duplicates products

8494
8494

In [4]:
# aggregate the reviews dfs into a single df

reviews_list = ["reviews_0-250.csv", "reviews_250-500.csv", "reviews_500-750.csv", "reviews_750-1250.csv", "reviews_1250-end.csv"]
reviews_df = pd.concat([pd.read_csv(f"{path}/{review}", low_memory=False) for review in reviews_list])

review_path = "../data/processed"
if not os.path.exists(review_path):
    os.makedirs(review_path)

reviews_df.to_csv(f"../data/processed/all_reviews.csv", index=False, sep=";")

In [5]:
reviews_df = pd.read_csv(f"../data/processed/all_reviews.csv", sep=";", low_memory=False, lineterminator='\n')
reviews_df.columns

Index(['Unnamed: 0', 'author_id', 'rating', 'is_recommended', 'helpfulness',
       'total_feedback_count', 'total_neg_feedback_count',
       'total_pos_feedback_count', 'submission_time', 'review_text',
       'review_title', 'skin_tone', 'eye_color', 'skin_type', 'hair_color',
       'product_id', 'product_name', 'brand_name', 'price_usd'],
      dtype='object')

In [6]:
reviews_df.drop(columns=["Unnamed: 0"], inplace=True)
reviews_df.sample(5)

,author_id,rating,is_recommended,helpfulness,total_feedback_count,total_neg_feedback_count,total_pos_feedback_count,submission_time,review_text,review_title,skin_tone,eye_color,skin_type,hair_color,product_id,product_name,brand_name,price_usd
550765,5426604911,5,NaN,1.000000,2,0,2,2016-11-06,I bought this because a YouTuber I watch made ...,MIRACLE WORKER,NaN,NaN,combination,NaN,P434360,High-Potency Night-a-Mins Resurfacing Cream wi...,Origins,52.0
822307,5216437010,5,1.0,0.857143,7,1,6,2019-03-16,"First of all, I’m obsessed! I was leery becaus...",Amazing peel pads!!,fair,hazel,normal,brown,P442742,Peptide 21 Amino Acid Exfoliating Peel Pads,Peter Thomas Roth,55.0
45289,8658929647,4,1.0,0.938462,65,4,61,2019-01-26,This product literally changed my life. For al...,Changed my life!!!,light,brown,combination,brown,P269122,Alpha Beta Extra Strength Daily Peel Pads,Dr. Dennis Gross Skincare,92.0
432998,5827100339,5,1.0,NaN,0,0,0,2018-08-10,love the smell love the feel love it every mor...,FAB,light,brown,combination,brown,P415237,Hello FAB Coconut Skin Smoothie Priming Moistu...,First Aid Beauty,32.0
806795,6650087695,5,1.0,1.000000,5,0,5,2021-09-19,My new fav YTTP product! Gentle enough to use ...,NaN,lightMedium,brown,combination,brown,P475630,Mini Mandelic Acid + Superfood Unity Exfoliant,Youth To The People,16.0

In [7]:
reviews_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1094411 entries, 0 to 1094410
Data columns (total 18 columns):
 #   Column                    Non-Null Count    Dtype
---  ------                    --------------    -----
 0   author_id                 1094411 non-null  object
 1   rating                    1094411 non-null  int64
 2   is_recommended            926423 non-null   float64
 3   helpfulness               532819 non-null   float64
 4   total_feedback_count      1094411 non-null  int64
 5   total_neg_feedback_count  1094411 non-null  int64
 6   total_pos_feedback_count  1094411 non-null  int64
 7   submission_time           1094411 non-null  object
 8   review_text               1092967 non-null  object
 9   review_title              783757 non-null   object
 10  skin_tone                 923872 non-null   object
 11  eye_color                 884783 non-null   object
 12  skin_type                 982854 non-null   object
 13  hair_color                867643 non-null   object
 14  product_id                1094411 non-null  object
 15  product_name              1094411 non-null  object
 16  brand_name                1094411 non-null  object
 17  price_usd                 1094411 non-null  float64
dtypes: float64(3), int64(4), object(11)
memory usage: 150.3+ MB

In [8]:
# check how many unique products are being reviewed 
reviews_df["product_id"].nunique()

# so a lot of products don't have any reviews

2351

In [9]:
merged_df = pd.merge(reviews_df, products_df, on="product_id", how="left")
merged_df.sample(5)

,author_id,rating_x,is_recommended,helpfulness,total_feedback_count,total_neg_feedback_count,total_pos_feedback_count,submission_time,review_text,review_title,...,brand_name_x,price_usd_x,product_name_y,brand_name_y,loves_count,rating_y,reviews,ingredients,price_usd_y,primary_category
568508,23055581092,5,1.0,1.000000,1,0,1,2022-12-30,I received th product as a sample. I have used...,Softer and brighter skin,...,belif,45.0,Aqua Bomb Brightening Vitamin C Cream,belif,19491,4.4992,1242.0,"['Water, Dimethicone, Propanediol, Glycerin, D...",45.0,Skincare
1056526,6273143470,5,1.0,NaN,0,0,0,2022-08-09,I’m excited to have received this amazing oil-...,Great Hydration & Radiance,...,Dr. Dennis Gross Skincare,72.0,Vitamin C Lactic Oil-Free Radiant Moisturizer,Dr. Dennis Gross Skincare,6654,4.6577,111.0,"['Water/Aqua/Eau, Squalane, Glycerin, 3-OEthyl...",72.0,Skincare
110481,5965984144,5,1.0,NaN,0,0,0,2018-07-13,I had to wait 2 months for this item to be in ...,NaN,...,Dr. Jart+,21.0,Mini Cicapair Tiger Grass Color Correcting Tre...,Dr. Jart+,74947,4.0165,5028.0,"['Water, Centella Asiatica Leaf Water, Isonony...",21.0,Skincare
210587,9108720965,1,0.0,0.818182,11,2,9,2021-03-11,I bought the Glow Recipe Best Sellers set and ...,Beware.,...,Glow Recipe,15.0,Mini Watermelon Glow PHA + BHA Pore-Tight Toner,Glow Recipe,111141,4.3728,3305.0,"['Opuntia Ficus-Indica (Cactus) Extract, Citru...",15.0,Skincare
344237,6082511027,4,1.0,NaN,0,0,0,2020-09-09,i wish i had more than a weeks worth of produc...,NaN,...,Estée Lauder,195.0,Advanced Night Repair Synchronized Multi-Recov...,Estée Lauder,11269,4.0456,2410.0,"['Water\\Aqua\\Eau, Bifida Ferment Lysate, Peg...",195.0,Skincare

In [10]:
columns = merged_df.columns.tolist()