# EDA

In [1]:
import pandas as pd

path = "../data/raw" 
products_df = pd.read_csv(f"{path}/product_info.csv")
products_df.columns

Index(['product_id', 'product_name', 'brand_id', 'brand_name', 'loves_count',
       'rating', 'reviews', 'size', 'variation_type', 'variation_value',
       'variation_desc', 'ingredients', 'price_usd', 'value_price_usd',
       'sale_price_usd', 'limited_edition', 'new', 'online_only',
       'out_of_stock', 'sephora_exclusive', 'highlights', 'primary_category',
       'secondary_category', 'tertiary_category', 'child_count',
       'child_max_price', 'child_min_price'],
      dtype='object')

In [2]:
use_cols = ["product_id","product_name", "brand_name", "loves_count", "rating", "reviews", "ingredients", "price_usd", "primary_category"]
products_df = products_df[use_cols]
products_df.sample(5)

,product_id,product_name,brand_name,loves_count,rating,reviews,ingredients,price_usd,primary_category
2599,P454333,Plush Eyeshadow Brush 240,Fenty Beauty by Rihanna,11515,4.7500,4.0,NaN,24.0,Makeup
566,P469203,They're Real! Magnet Extreme Lengthening Mascara,Benefit Cosmetics,18387,4.1660,4483.0,"['Aqua (Water), Cera Alba (Beeswax), Paraffin,...",28.0,Makeup
5874,P447519,Sublime Perfection Foundation,PAT McGRATH LABS,122029,4.1832,1938.0,"['Water, Cyclopentasiloxane, Isododecane, Alco...",68.0,Makeup
78,P460780,Hibiscus Palm Eau de Parfum Travel Spray,AERIN,3549,4.0714,14.0,"['Alcohol Denat., Fragrance (Parfum), Water\\A...",35.0,Fragrance
1349,P467755,Hydrating Toner Lotion with Aloe Vera,Clarins,3710,3.8462,13.0,"['Aqua/Water/Eau, Aloe Barbadensis Leaf Juice,...",30.0,Skincare

In [3]:
print(len(products_df))
print(products_df["product_id"].nunique()) # checking for duplicates products

8494
8494

In [4]:
# aggregate the reviews dfs into a single df

# reviews_list = ["reviews_0-250.csv", "reviews_250-500.csv", "reviews_500-750.csv", "reviews_750-1250.csv", "reviews_1250-end.csv"]
# reviews_df = pd.concat([pd.read_csv(f"{path}/{review}", low_memory=False) for review in reviews_list])

# reviews_df.to_csv(f"../data/processed/all_reviews.csv", index=False, sep=";")

In [5]:
reviews_df = pd.read_csv(f"../data/processed/all_reviews.csv", sep=";", low_memory=False, lineterminator='\n')
reviews_df.columns

FileNotFoundError: [Errno 2] No such file or directory: '../data/processed/all_reviews.csv'

In [ ]:
reviews_df.drop(columns=["Unnamed: 0"], inplace=True)
reviews_df.sample(5)

,author_id,rating,is_recommended,helpfulness,total_feedback_count,total_neg_feedback_count,total_pos_feedback_count,submission_time,review_text,review_title,skin_tone,eye_color,skin_type,hair_color,product_id,product_name,brand_name,price_usd
32521,1547183187,5,NaN,1.0,5,0,5,2009-08-27,When I hit 40 everything changed on my face......,it REALLY works,lightMedium,NaN,combination,NaN,P218700,100 percent Pure Argan Oil,Josie Maran,49.0
77141,1825061419,5,1.0,1.0,3,0,3,2020-03-31,This is my favourite gel cleaner! A little goe...,best gel cleanser,light,green,dry,brown,P411387,Superfood Antioxidant Cleanser,Youth To The People,39.0
922803,5096556824,5,1.0,NaN,0,0,0,2020-03-04,This moisturizer is really nice! It has a nice...,love it!,fair,brown,normal,brown,P456193,The Afterglow Deep Moisturizing Cream with Hya...,Prima,68.0
1036282,7039500215,5,1.0,1.0,1,0,1,2021-04-23,"I love this, it’s relaxing and actually does m...",MUST BUY.,medium,hazel,combination,blonde,P461520,Clean Foot Mask,SEPHORA COLLECTION,5.0
569748,1374275600,5,1.0,1.0,9,0,9,2022-09-24,I read all of the reviews. My skin likes Ole p...,"Trust me….Don’t buy 1 bottle, buy 2!",lightMedium,brown,combination,brown,P434545,Glow Cycle Retin-ALT Power Serum,OLEHENRIKSEN,60.0

In [ ]:
reviews_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1094411 entries, 0 to 1094410
Data columns (total 18 columns):
 #   Column                    Non-Null Count    Dtype
---  ------                    --------------    -----
 0   author_id                 1094411 non-null  object
 1   rating                    1094411 non-null  int64
 2   is_recommended            926423 non-null   float64
 3   helpfulness               532819 non-null   float64
 4   total_feedback_count      1094411 non-null  int64
 5   total_neg_feedback_count  1094411 non-null  int64
 6   total_pos_feedback_count  1094411 non-null  int64
 7   submission_time           1094411 non-null  object
 8   review_text               1092967 non-null  object
 9   review_title              783757 non-null   object
 10  skin_tone                 923872 non-null   object
 11  eye_color                 884783 non-null   object
 12  skin_type                 982854 non-null   object
 13  hair_color                867643 non-null   object
 14  product_id                1094411 non-null  object
 15  product_name              1094411 non-null  object
 16  brand_name                1094411 non-null  object
 17  price_usd                 1094411 non-null  float64
dtypes: float64(3), int64(4), object(11)
memory usage: 150.3+ MB

In [ ]:
# check how many unique products are being reviewed 
reviews_df["product_id"].nunique()

# so a lot of products don't have any reviews

2351

In [ ]:
merged_df = pd.merge(reviews_df, products_df, on="product_id", how="left")
merged_df.sample(5)

,author_id,rating_x,is_recommended,helpfulness,total_feedback_count,total_neg_feedback_count,total_pos_feedback_count,submission_time,review_text,review_title,...,brand_name_x,price_usd_x,product_name_y,brand_name_y,loves_count,rating_y,reviews,ingredients,price_usd_y,primary_category
194296,8424259581,5,1.0,NaN,0,0,0,2019-09-13,This was super refreshing and hydrating withou...,NaN,...,Bobbi Brown,66.0,Vitamin Enriched Face Base Priming Moisturizer,Bobbi Brown,171118,4.6058,3440.0,"['Water\\Aqua\\Eau, Cyclopentasiloxane, Bis-Di...",66.0,Skincare
850383,1325857420,4,NaN,NaN,0,0,0,2015-05-03,"I’ve only used this once, after buying as a po...",pretty good,...,Shiseido,70.0,Benefiance WrinkleResist24 Pure Retinol Expres...,Shiseido,81341,4.4220,500.0,"['Water, Butylene Glycol, Pentaerythrityl Tetr...",70.0,Skincare
1062972,6107364525,5,NaN,1.0,30,0,30,2016-05-27,I have had trouble skin since having my second...,The Perfect Addition,...,Tata Harper,88.0,Nourishing Makeup Removing Oil Cleanser,Tata Harper,9393,4.0211,95.0,"['Helianthus Annuus (Sunflower) Seed Oil*, Ole...",88.0,Skincare
973757,1273290556,5,1.0,1.0,1,0,1,2020-06-03,I really like this mask! After I use it my ski...,A Healthy Hydrated Glow,...,Dr. Jart+,7.0,Dermask Water Jet Vital Hydra Solution,Dr. Jart+,40090,4.5507,276.0,"['Water, Glycerin, Butylene Glycol, Alcohol, P...",7.0,Skincare
838818,1125082615,5,1.0,NaN,0,0,0,2019-04-09,Made my skin super smooth and really helped wi...,Great for sensitive skin,...,Sunday Riley,85.0,A+ High-Dose Retinol Serum,Sunday Riley,66551,4.2016,516.0,"['Water, Propanediol, Dimethyl Isosorbide, Tri...",85.0,Skincare

In [ ]:
columns = merged_df.columns.tolist()